### ISSUE TITLE
Can't edit promocode, backoffice showing blank

### ISSUE THREAD

**Issue by binary-karen** [binary-com/binary-static#227]
Hi, 

Can't access this page to edit the promocode: 

https://collector01.binary.com/d/backoffice/promocode_edit.cgi?promocode=17162F10&broker=CR

![promocode](https://cloud.githubusercontent.com/assets/8100496/6749014/f7fcf6ec-cf26-11e4-943b-f5bb33f427d1.png)

**Comment by binary-karen** [comment]
Tried adding a new one, nothing happened too.

**Comment by raunakkathuria** [comment]
This should not be open on binary-static one as it is internal to us. If possible open it on business one and assign it to me. Will check
