### ISSUE TITLE
Trading panel alignment is not proper

### ISSUE THREAD

**Issue by ehteshamy2k** [binary-com/binary-static#232]
Trading panel alignment is not proper. Live website has better alignment.

![image](https://cloud.githubusercontent.com/assets/8477011/6804868/e03549b8-d261-11e4-9c98-b8031588a61d.png)

**Comment by borisyankov** [comment]
Layout with live site is the same.
The difference here is that you have the 'Trading is suspended' notifications that make the right column higher.
