### ISSUE TITLE
Mobile interface doesn't indicate which type of trading is taking place

### ISSUE THREAD

**Issue by ehteshamy2k** [binary-com/binary-static#233]
Mobile interface doesn't indicate which type of trading is taking place

![image](https://cloud.githubusercontent.com/assets/8477011/6805893/55cea570-d267-11e4-828c-4638601a0d51.png)

**Comment by borisyankov** [comment]
It has been like that for ages.
The navigation is hidden in the 'hamburger' menu and needs a full rework anyways.
