### ISSUE TITLE
Mobile interface doesn't show error message correctly when flipped

### ISSUE THREAD

**Issue by ehteshamy2k** [binary-com/binary-static#234]
Mobile interface doesn't show error message correctly when flipped. Without flipping it doesnt show error message at all.

![image](https://cloud.githubusercontent.com/assets/8477011/6806003/fc40d4fa-d267-11e4-929f-5245998b0105.png)

**Comment by raunakkathuria** [comment]
@ehteshamy2k Can you please provide the resolution on which you checked this in future so that we are on same page

**Comment by borisyankov** [comment]
This is a bug that is relevant to binary.com too.
Between 480 and 580 pixels in width, the layout is crappy.
