### ISSUE TITLE
Pull request 271 - Internal server error occur on updating "Second line of home address"

### ISSUE THREAD

**Issue by ehteshamy2k** [binary-com/binary-static#274]
Internal server error occur on when user updated "Second line of home address" on settings page

![image](https://cloud.githubusercontent.com/assets/8477011/7684078/c7795976-fd9c-11e4-83e2-64942da0a4b6.png)

**Comment by fayland** [comment]
Please give it a try again. Thanks

**Comment by ehteshamy2k** [comment]
Closing it as error no more appears
