### ISSUE TITLE
Pull request 271 - Cashier session expires on "https://www.binaryqa01.com/cashier/forward?l=EN" page

### ISSUE THREAD

**Issue by ehteshamy2k** [binary-com/binary-static#275]
Cashier session expires on "https://www.binaryqa01.com/cashier/forward?l=EN" page

![image](https://cloud.githubusercontent.com/assets/8477011/7684255/1af74ada-fd9e-11e4-96d7-e64a9814be9f.png)

**Comment by fayland** [comment]
that's acknowledged. cashier testing in qa is not using forward.
