### ISSUE TITLE
Reality check - Virtual account details are not available in pop up as shown in sample screenshot

### ISSUE THREAD

**Issue by ehteshamy2k** [binary-com/binary-static#280]
Virtual account details are not available in pop up as shown in sample screenshot

Following is sample screenshot:
![image](https://cloud.githubusercontent.com/assets/8477011/7721594/5ee04490-fef2-11e4-9550-a9b5dedd81c8.png)

Please see that attached screenshot (below) doesn't have virtual account details:

![image](https://cloud.githubusercontent.com/assets/8477011/7721584/4650b996-fef2-11e4-907f-15d2f79981d6.png)

**Comment by tfoertsch** [comment]
The sample screenshot was taken on my devbox to show how it would look like with 2 accounts and why this is a table. In theory, we can have multiple currencies per loginid and different loginids with different landing companies. The reality-check feature applies only to MLT and MF landing companies. QA is not different in that regard from production. And, in reality, there is currently no way to create an MF account nor multiple segments per account. Hence, on qa, there can only be one row in that table per user, namely the MLT account with one segment.
