### ISSUE TITLE
Reality Check - Pop up layout is distorted on Android

### ISSUE THREAD

**Issue by ehteshamy2k** [binary-com/binary-static#284]
Pop up layout is distorted on Android
![screenshot_2015-05-20-17-13-26](https://cloud.githubusercontent.com/assets/8477011/7725646/ec676636-ff15-11e4-9c3f-479880694899.png)

**Comment by borisyankov** [comment]
We are using some different code there, than the normal (crappy) one.
I will want to rework it completely, to not suck, and look good on mobile too.

Let's keep this like that, and once we ship the redesign to production, I'll rework all modals.

**Comment by ehteshamy2k** [comment]
Ok, I will review it once it is fixed and assigned back to me.
