### ISSUE TITLE
Reality Check doesn't appear if no option is selected and site is closed/reopened

### ISSUE THREAD

**Issue by bijan2007** [binary-com/binary-static#286]
Steps:
1. Wait for the Reality Check to appear
2. Don't select any option
3. Close the binary site/browser
4. Open the binary site again
Expected - Reality Check re appears on the binary site
Actual - Reality Check doesn't appear on the site

**Comment by tfoertsch** [comment]
The URL in point 4 is the home page. Not sure if that page should display the reality check. This might or might not be a bug.
