### ISSUE TITLE
how to connect database

### ISSUE THREAD

**Issue by phanchaulong** [binary-com/binary-static#3917]
I did not find the database connection. Please help

**Comment by binary-hamedanchi** [comment]
@phanchaulong 

It connects to [Binary.com API](https://developers.binary.com/) through a [WebSocket](https://developer.mozilla.org/en-US/docs/Web/API/WebSocket) connection.

Here you can find code samples written in different languages on how to connect to the API:
https://developers.binary.com/demos/

In this repo, it's done [here](https://github.com/binary-com/binary-static/blob/d47c7f7db46b0d88da60cbdbe4bf3a5bbb28b828/src/javascript/_common/base/socket_base.js#L203).

Regards.

**Comment by phanchaulong** [comment]
how to clone a database and download to local. how can i run the database on my computer.
Thanks so much

**Comment by ashkanx** [comment]
@phanchaulong   
all information is available here: https://developers.binary.com/ 
please study the link and let us know if you have any questions.

Cheers,
