### ISSUE TITLE
Contact Us, Email error messaging incorrect with attachment >1M

### ISSUE THREAD

**Issue by gryphonbinary** [binary-com/binary-static#61]
Reproduce as follows:

1. Go to "Contact Us", then "Email Us"
2. Fill out the form
3. Attach file larger than 1M
4. Click "Send"

Instead of submitting successfully, the same page loads with a blank form and error messaging displayed such as "Name too short", "Please enter your email address" and "Message is too short".

There should instead be an error message that indicates the file is too large and tells what the max file size allowed is. Consider also raising the limit from 1M to 2M.

This was originally reported under [Business Issue #11](https://github.com/regentmarkets/business/issues/11 "Business Issue #11").

**Comment by raunakkathuria** [comment]
We have refactored the contact us page to remove the form, its just a static page now
